// Code generated by MockGen. DO NOT EDIT.
// Source: factory.go

// Package fitbit2gcal is a generated GoMock package.
package fitbit2gcal

import (
	fitbitauth "github.com/go-zen-chu/gae-fitbit-go/pkg/domain/fitbitauth"
	gcalauth "github.com/go-zen-chu/gae-fitbit-go/pkg/domain/gcalauth"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockFactory is a mock of Factory interface
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// Service mocks base method
func (m *MockFactory) Service(fitbitConfig *FitbitConfig, gcalConfig *GCalConfig, fbst fitbitauth.Store, gst gcalauth.Store) Service {
	ret := m.ctrl.Call(m, "Service", fitbitConfig, gcalConfig, fbst, gst)
	ret0, _ := ret[0].(Service)
	return ret0
}

// Service indicates an expected call of Service
func (mr *MockFactoryMockRecorder) Service(fitbitConfig, gcalConfig, fbst, gst interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Service", reflect.TypeOf((*MockFactory)(nil).Service), fitbitConfig, gcalConfig, fbst, gst)
}

// FitbitClient mocks base method
func (m *MockFactory) FitbitClient(store fitbitauth.Store, fitbitConfig *FitbitConfig) FitbitClient {
	ret := m.ctrl.Call(m, "FitbitClient", store, fitbitConfig)
	ret0, _ := ret[0].(FitbitClient)
	return ret0
}

// FitbitClient indicates an expected call of FitbitClient
func (mr *MockFactoryMockRecorder) FitbitClient(store, fitbitConfig interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FitbitClient", reflect.TypeOf((*MockFactory)(nil).FitbitClient), store, fitbitConfig)
}

// GCalClient mocks base method
func (m *MockFactory) GCalClient(store gcalauth.Store, gcalConfig *GCalConfig) GCalClient {
	ret := m.ctrl.Call(m, "GCalClient", store, gcalConfig)
	ret0, _ := ret[0].(GCalClient)
	return ret0
}

// GCalClient indicates an expected call of GCalClient
func (mr *MockFactoryMockRecorder) GCalClient(store, gcalConfig interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GCalClient", reflect.TypeOf((*MockFactory)(nil).GCalClient), store, gcalConfig)
}
