// Code generated by MockGen. DO NOT EDIT.
// Source: store.go

// Package gcalauth is a generated GoMock package.
package gcalauth

import (
	gomock "github.com/golang/mock/gomock"
	oauth2 "golang.org/x/oauth2"
	reflect "reflect"
)

// MockStore is a mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// WriteGCalTokens mocks base method
func (m *MockStore) WriteGCalTokens(token *oauth2.Token) error {
	ret := m.ctrl.Call(m, "WriteGCalTokens", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteGCalTokens indicates an expected call of WriteGCalTokens
func (mr *MockStoreMockRecorder) WriteGCalTokens(token interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteGCalTokens", reflect.TypeOf((*MockStore)(nil).WriteGCalTokens), token)
}

// FetchGCalTokens mocks base method
func (m *MockStore) FetchGCalTokens() (*oauth2.Token, error) {
	ret := m.ctrl.Call(m, "FetchGCalTokens")
	ret0, _ := ret[0].(*oauth2.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGCalTokens indicates an expected call of FetchGCalTokens
func (mr *MockStoreMockRecorder) FetchGCalTokens() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGCalTokens", reflect.TypeOf((*MockStore)(nil).FetchGCalTokens))
}
