// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package auth is a generated GoMock package.
package auth

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// HandleFitbitAuthCode mocks base method
func (m *MockService) HandleFitbitAuthCode(code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleFitbitAuthCode", code)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleFitbitAuthCode indicates an expected call of HandleFitbitAuthCode
func (mr *MockServiceMockRecorder) HandleFitbitAuthCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFitbitAuthCode", reflect.TypeOf((*MockService)(nil).HandleFitbitAuthCode), code)
}

// HandleGCalAuthCode mocks base method
func (m *MockService) HandleGCalAuthCode(code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGCalAuthCode", code)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleGCalAuthCode indicates an expected call of HandleGCalAuthCode
func (mr *MockServiceMockRecorder) HandleGCalAuthCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGCalAuthCode", reflect.TypeOf((*MockService)(nil).HandleGCalAuthCode), code)
}
